### ISSUE TITLE
Tileserver-GL

### ISSUE THREAD

**Issue by utagawal** [markusand/mapboxgl-legend#14]
Hello,

Is the project compatible with https://openmaptiles.org/ and Tileserver-GL serving mapbox compatible tiles from a Docker container ?

**Comment by markusand** [comment]
If I'm not mistaken, openmaptiles is providing the source for mapbox. The legend is source agnostic, but reacting at `styledata` event. As long as you're using mapbox with [expressions](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/) I can't see a reason why it should't work. You could try and comment back here :)
