### ISSUE TITLE
Custom marker support?

### ISSUE THREAD

**Issue by aliceahalsted** [markusand/mapboxgl-legend#19]
Just found your repo and it's pretty cool - have you thought of adding support for custom markers?  I have a map that uses a local file with custom markers and since it doesn't get added as a regular layer it doesn't look like I can get it to show up in the legend.

**Comment by markusand** [comment]
I'm not sure I understand your question. If you mean to add mapboxgl.Marker() that it's not possible, this library parses layer definitions from map.addLayer() whenever there's a layer event triggered.

One thing you can do is to add a symbol layer and get the library render your symbols such as follows
<img width="549" alt="Captura de pantalla 2023-08-05 a les 5 39 02 p  m" src="https://github.com/markusand/mapboxgl-legend/assets/12972543/62b5af38-aac7-4b9c-b7a1-081786d11db6">

**Comment by aliceahalsted** [comment]
I was thinking maybe an option where one could add to the legend manually for things that wouldn't get parsed.
