### ISSUE TITLE
Raster layer support

### ISSUE THREAD

**Issue by am2222** [markusand/mapboxgl-legend#20]
Hi,
Is it possible to support the raster layer? Like when we have a TMS or wms layer which has color classes (like a landcover map).

We have discrate, classified and continues rasters. I see legend already supports such data type. I feel we can read these information from layer metadata when source type is raster. A descrate and classifoed raster can have oprion to manually feed classes/color as key value pair and for the continues raster we can have a color ramp or an array of colors (max 100).

I can add its PR if you think this is something we can add to this project.

**Comment by markusand** [comment]
Mapbox raster layers have no paint properties for styling https://docs.mapbox.com/style-spec/reference/layers/#raster. You can't set a list of colors or a ramp for elements, as the raster itself it's just an image and it's not styled in the client.

**Comment by markusand** [comment]
For this specific case I suggest to simply create an overlay ul and fill it with all the content you'd like it to have. This library relies in events and layer modelling from Mapbox, adding such a feature means to create a totally new legend.

**Comment by am2222** [comment]
@markusand That sounds great. However I am using react and manipulating HTML dom outside of the react seems to be discouraged. I will try it tho.

Thanks!
