### ISSUE TITLE
Add maplibre-gl-js compatibility

### ISSUE THREAD

**Issue by IncidGeo** [markusand/mapboxgl-legend#22]
Hi,
I'd like to know if this library is also working with maplibre-gl-js ?

**Comment by markusand** [comment]
Hi. This library is tightly coupled to Mapbox's Control interface and events. I haven't worked with Maplibre, but it seems that Control is the same as Mapbox. As long as it emits the same events and include the same properties, it could potentialy work. I suggest you to try and tell us ☺️

**Comment by IncidGeo** [comment]
Thank you markusand for your answer, it does not seems to work directly
To use MapboxDraw in Maplibre i need to add :
MapboxDraw.constants.classes.CONTROL_BASE = 'maplibregl-ctrl';
MapboxDraw.constants.classes.CONTROL_PREFIX = 'maplibregl-ctrl-';
MapboxDraw.constants.classes.CONTROL_GROUP = 'maplibregl-ctrl-group';

I try to understand it.

**Comment by IncidGeo** [comment]
I' had a look to the code, what a nice library ! I won't use 1/100 of the code so I've finally wrote my own code, just need to read the match expression in the map style. It would be very nice to have it for Maplibre, i'm not competent enough to convert it.

**Comment by rcoup** [comment]
So my 10-minute exercise got it working — the only changes I made were css classes:

* `maplibregl-ctrl` is the equivalent to `mapboxgl-ctrl`
* likewise `mapboxgl-ctrl-bottom-right` is the equivalent to `mapboxgl-bottom-right`, etc

This doesn't touch the Typescript or the tests, but I found a post on plugins using union types to unify the interfaces https://maplibre.org/news/2023-01-03-aws-maplibre-plugins/

Beyond the demo changes, the CSS/SCSS changes are compatible across both.

```diff
diff --git a/index.html b/index.html
index c930f1d..6d1f2a9 100644
--- a/index.html
+++ b/index.html
@@ -4,8 +4,8 @@
     <meta charset="utf-8" />
     <title>MapboxGL LegendControl example</title>
     <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
-    <script src="https://api.mapbox.com/mapbox-gl-js/v2.0.0/mapbox-gl.js"></script>
-    <link href="https://api.mapbox.com/mapbox-gl-js/v2.0.0/mapbox-gl.css" rel="stylesheet" />
+    <script src="https://cdn.jsdelivr.net/npm/maplibre-gl@4/dist/maplibre-gl.min.js"></script>
+    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/maplibre-gl@4/dist/maplibre-gl.min.css">
     <style>
       body {
         margin: 0;
@@ -24,15 +24,14 @@
   <body>
     <div id="map"></div>
     <script type="module" lang="ts">
-      import { Map } from 'mapbox-gl';
+      import { Map } from 'maplibre-gl';
       import LegendControl from './src';

       const map = new Map({
         container: 'map',
-        style: 'mapbox://styles/mapbox/light-v10',
+        style: 'https://demotiles.maplibre.org/style.json',
         zoom: 12,
         center: [-122.447303, 37.753574],
-        accessToken: import.meta.env.VITE_MAPBOX_TOKEN,
       });

       const legend = new LegendControl({
diff --git a/package.json b/package.json
index 6f7f57f..c400781 100644
--- a/package.json
+++ b/package.json
@@ -56,6 +56,7 @@
     "eslint-import-resolver-typescript": "^3.5.4",
     "jsdom": "^23.2.0",
     "mapbox-gl": "^3.1.0",
+    "maplibre-gl": "^4.7.1",
     "sass": "^1.60.0",
     "stylelint": "^16.2.0",
     "stylelint-config-standard-scss": "^13.0.0",
diff --git a/src/LegendControl.ts b/src/LegendControl.ts
index e9912bf..891d080 100644
--- a/src/LegendControl.ts
+++ b/src/LegendControl.ts
@@ -49,7 +49,7 @@ export default class LegendControl implements IControl {
       }) : undefined;

     this._container = createElement('div', {
-      classes: ['mapboxgl-ctrl', 'mapboxgl-ctrl-legend'],
+      classes: ['mapboxgl-ctrl', 'maplibregl-ctrl', 'mapboxgl-ctrl-legend'],
       content: [this._minimizer, this._panes],
     });

diff --git a/src/styles/main.scss b/src/styles/main.scss
index da29af3..f2e7ff6 100644
--- a/src/styles/main.scss
+++ b/src/styles/main.scss
@@ -82,9 +82,13 @@
     }
   }

+  .maplibregl-ctrl-bottom-right &,
+  .maplibregl-ctrl-top-right &,
   .mapboxgl-ctrl-bottom-right &,
   .mapboxgl-ctrl-top-right & { align-items: flex-end; }

+  .maplibregl-ctrl-bottom-right &,
+  .maplibregl-ctrl-bottom-left &,
   .mapboxgl-ctrl-bottom-right &,
   .mapboxgl-ctrl-bottom-left & { flex-direction: column-reverse; }

```

**Comment by markusand** [comment]
Such an easy interoperability with Mapblibre looks really great! I'll try to implement this when I have some time. Indeed, PRs are welcome 😊
