### ISSUE TITLE
Layers group

### ISSUE THREAD

**Issue by sylvain258** [markusand/mapboxgl-legend#23]
Hello, 

Is it possible to group layers ? For example, layers relative to demography together, layers relatives to the nature together etc.

Thank you for your feedback,

Sylvain Becquaert

**Comment by markusand** [comment]
Panels are created from the layers you define in Mapbox. As long as there are different layers, it's not possible to group them right now.

That said, there's the option to toggle multiple layers with a single toggler. Hope this helps.

```js
const legend = new LegendControl({
  layers: {
    lakes: true,
    rivers: {
      toggler: ['rivers', 'lakes'],
    },
  },
})
```
